# Generated by Django 2.1.7 on 2019-03-21 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import extensionworkers.models.individual
import extensionworkers.models.organization


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('workStatus', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='FurtherTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('field', models.CharField(max_length=100)),
                ('started', models.DateField()),
                ('finished', models.DateField()),
            ],
            options={
                'verbose_name': 'FurtherTraining',
                'verbose_name_plural': 'FurtherTrainings',
                'db_table': 'further_training',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('', '[Select Gender]'), ('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('postalAddress', models.TextField()),
                ('physicalAddress', models.TextField()),
                ('profile_picture', models.FileField(upload_to=extensionworkers.models.individual.user_directory_path)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individual',
                'db_table': 'individual',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('central_districts', models.TextField(blank=True, null=True)),
                ('eastern_districts', models.TextField(blank=True, null=True)),
                ('northern_districts', models.TextField(blank=True, null=True)),
                ('western_districts', models.TextField(blank=True, null=True)),
                ('key_beneficiaries', models.CharField(choices=[('', '[Select Key Beneficiaries]'), ('Farmers', 'Farmers'), ('Students', 'Students'), ('Field Extension workers', 'Field Extension workers')], max_length=40)),
                ('farmer_category', models.CharField(choices=[('', '[Select Farmer category]'), ('All Farmers', 'All Farmers'), ('Rural', 'Rural'), ('Peri-Urban', 'Peri-Urban')], max_length=30)),
                ('farmer_gender', models.CharField(choices=[('', '[Select Farmer gender]'), ('All Genders', 'All Genders'), ('Women', 'Women'), ('Youth', 'Youth')], max_length=30)),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'db_table': 'operations',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('institution', models.CharField(max_length=100)),
                ('registrationDate', models.DateField(blank=True, null=True)),
                ('legalRegistrationEntityNo', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('postalAddress', models.TextField()),
                ('district', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(upload_to=extensionworkers.models.organization.user_directory_path)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Operation')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('field', models.CharField(choices=[('', '[Select Field]'), ('Crop', 'Crop'), ('Animal Science', 'Animal Science'), ('Fisheries', 'Fisheries'), ('Forestry', 'Forestry')], max_length=20)),
                ('qualification', models.CharField(choices=[('', '[Select Qualification]'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('BSc.', 'BSc.'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=100)),
                ('isFurtherTraining', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sector', models.CharField(choices=[('', '[Select sector]'), ('Public', 'Public'), ('Private', 'Private'), ('Academia', 'Academia'), ('NGO', 'NGO'), ('Farmers Organization ', 'Farmers Organization ')], max_length=40)),
                ('agricultural_sector_focus', models.CharField(choices=[('', '[Select option]'), ('General', 'General'), ('Specific', 'Specific')], max_length=20)),
                ('animal_production', models.CharField(choices=[('', '[Select option]'), ('All', 'All'), ('Large livestock(cattle)', 'Large livestock(cattle)'), ('small livestock(Sheep, goats', 'small livestock(Sheep, goats'), ('Micro livestock(Rabbits)  ', 'Micro livestock(Rabbits)  '), ('Birds(Chicken, Turkeys, ducks)', 'Birds(Chicken, Turkeys, ducks)'), ('Bees', 'Bees'), ('Fisheries', 'Fisheries')], max_length=100, null=True)),
                ('crop_production', models.CharField(choices=[('', '[Select option]'), ('All', 'All'), ('Traditional cash crops ( tea, cocoa, coffee, sugarcanes)', 'Traditional cash crops ( tea, cocoa, coffee, sugarcanes)'), ('Cereals and legumes (maize, rice, sorghum, beans, soya, cowpeas, etc)', 'Cereals and legumes (maize, rice, sorghum, beans, soya, cowpeas, etc)'), ('Bananas', 'Bananas'), ('Fruits and Vegetables', 'Fruits and Vegetables'), ('Commercial Trees', 'Commercial Trees')], max_length=200, null=True)),
                ('post_harvest_handling', models.BooleanField(default=False)),
                ('agribusiness_devt_services', models.BooleanField(default=False)),
                ('consultancy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('male_staff', models.PositiveIntegerField()),
                ('female_staff', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='TrainedStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('level', models.CharField(choices=[('', '[Select Level]'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('BSc.', 'BSc.'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=30)),
                ('maleStaff', models.PositiveIntegerField()),
                ('femaleStaff', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Trained Staff',
                'verbose_name_plural': 'Trained Staff',
                'db_table': 'trained_staff',
            },
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Verifier',
                'verbose_name_plural': 'Verifiers',
                'db_table': 'verifier',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Sector'),
        ),
        migrations.AddField(
            model_name='organization',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Staff'),
        ),
        migrations.AddField(
            model_name='organization',
            name='trained_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.TrainedStaff'),
        ),
        migrations.AddField(
            model_name='organization',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Verifier'),
        ),
        migrations.AddField(
            model_name='individual',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Operation'),
        ),
        migrations.AddField(
            model_name='individual',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Qualification'),
        ),
        migrations.AddField(
            model_name='individual',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Sector'),
        ),
        migrations.AddField(
            model_name='individual',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensionworkers.Verifier'),
        ),
    ]
